apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: andel-project-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: andel-project-webapi-config
    literals:
      - database=andel-project-q
      - collection=ambulance
patches:
- path: patches/webapi.deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: andel-project-webapi