/*
 * Questionnaire Api
 *
 * Patient questionnaire management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xandelt1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type QuestionnaireAPI interface {


    // CreateQuestionnaireEntry Post /api/questionnaire/:ambulanceId/entries
    // Vytvorí nový dotazník pre danú ambulanciu 
     CreateQuestionnaireEntry(c *gin.Context)

    // DeleteQuestionnaireEntry Delete /api/questionnaire/:ambulanceId/entries/:entryId
    // Odstráni konkrétny dotazník 
     DeleteQuestionnaireEntry(c *gin.Context)

    // GetQuestionnaireEntries Get /api/questionnaire/:ambulanceId/entries
    // Provides the ambulance questionnaire entries 
     GetQuestionnaireEntries(c *gin.Context)

    // GetQuestionnaireEntry Get /api/questionnaire/:ambulanceId/entries/:entryId
    // Poskytne detail konkrétneho dotazníka 
     GetQuestionnaireEntry(c *gin.Context)

    // UpdateQuestionnaireEntry Put /api/questionnaire/:ambulanceId/entries/:entryId
    // Aktualizuje konkrétny dotazník 
     UpdateQuestionnaireEntry(c *gin.Context)

}