/*
 * Questionnaire Api
 *
 * Patient questionnaire management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xandelt1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"time"
)

type Questionnaire struct {

	// Unique questionnaire entry ID
	Id string `json:"id"`

	// Patient’s full name
	Name string `json:"name"`

	// Patient identifier in Web-In-Cloud system
	PatientId string `json:"patientId"`

	// Last modification timestamp (ISO 8601)
	LastModified time.Time `json:"lastModified"`

	// Odpovede na otázky v pevne danom poradí (index 0 – 7)
	Questions []string `json:"questions"`
}
