openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Patient questionnaire management for Web-In-Cloud system
  version: "1.0.0"
  title: Questionnaire Api
  contact:
    email: xandelt1@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
  - name: questionnaire
    description: Questionnare API

paths:
  "/questionnaire/{ambulanceId}/entries":
    post:
      tags: [questionnaire]
      summary: Vytvorí nový dotazník pre danú ambulanciu
      operationId: createQuestionnaireEntry
      description: |
        Pridá nový záznam dotazníka.
      parameters:
        - in: path
          name: ambulanceId
          required: true
          description: ID ambulancie
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Questionnaire"
            examples:
              request:
                $ref: "#/components/examples/QuestionnaireExample"
      responses:
        "201":
          description: Dotazník úspešne vytvorený
          headers:
            Location:
              description: URI nového zdroja
              schema: { type: string }
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Questionnaire"
              examples:
                response:
                  $ref: "#/components/examples/QuestionnaireExample"
        "400":
          description: Neplatné dáta v tele požiadavky
        "404":
          description: Ambulancia s takým ID neexistuje
    get:
      tags: [questionnaire]
      summary: Provides the ambulance questionnaire entries
      operationId: getQuestionnaireEntries
      parameters:
        - in: path
          name: ambulanceId
          required: true
          description: ID ambulancie
          schema:
            type: string
      responses:
        "200":
          description: Zoznam dotazníkov pre danú ambulanciu
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Questionnaire"
              examples:
                default:
                  $ref: "#/components/examples/QuestionnaireArrayExample"
        "404":
          description: Ambulancia s takým ID neexistuje

  "/questionnaire/{ambulanceId}/entries/{entryId}":
    get:
      tags: [questionnaire]
      summary: Poskytne detail konkrétneho dotazníka
      operationId: getQuestionnaireEntry
      parameters:
        - in: path
          name: ambulanceId
          required: true
          schema: { type: string }
        - in: path
          name: entryId
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Detail dotazníka
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Questionnaire"
              examples:
                response:
                  $ref: "#/components/examples/QuestionnaireExample"
        "404":
          description: Ambulancia alebo dotazník s takým ID neexistuje

    put:
      tags: [questionnaire]
      summary: Aktualizuje konkrétny dotazník
      operationId: updateQuestionnaireEntry
      parameters:
        - in: path
          name: ambulanceId
          required: true
          schema: { type: string }
        - in: path
          name: entryId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Questionnaire"
            examples:
              request:
                $ref: "#/components/examples/QuestionnaireExample"
      responses:
        "200":
          description: Aktualizovaný dotazník
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Questionnaire"
              examples:
                response:
                  $ref: "#/components/examples/QuestionnaireExample"
        "403":
          description: entryId v URL a v tele požiadavky nesúhlasia
        "404":
          description: Ambulancia alebo dotazník s takým ID neexistuje

    delete:
      tags: [questionnaire]
      summary: Odstráni konkrétny dotazník
      operationId: deleteQuestionnaireEntry
      parameters:
        - in: path
          name: ambulanceId
          required: true
          schema: { type: string }
        - in: path
          name: entryId
          required: true
          schema: { type: string }
      responses:
        "204":
          description: Dotazník odstránený
        "404":
          description: Ambulancia alebo dotazník s takým ID neexistuje

components:
  schemas:
    Questionnaire:
      type: object
      required: [id, name, patientId, lastModified, questions]
      properties:
        id:
          type: string
          description: Unique questionnaire entry ID
          example: x321ab3
        name:
          type: string
          description: Patient’s full name
          example: Jožko Púčik
        patientId:
          type: string
          description: Patient identifier in Web-In-Cloud system
          example: 460527-jozef-pucik
        lastModified:
          type: string
          format: date-time
          description: Last modification timestamp (ISO 8601)
          example: "2038-12-24T10:05:00Z"
        questions:
          type: array
          description: Odpovede na otázky v pevne danom poradí (index 0 – 7)
          items:
            type: string
          example:
            - "Žiadne"
            - "Nie"
            - "Chronická nádcha"
            - "Nie"
            - "Nie"
            - "Áno, ale len občas"
            - "Fyzioterapia a masáže"
            - "Nie"

  examples:
    QuestionnaireExample:
      summary: Jeden dotazník
      value:
        id: x321ab3
        name: "Jožko Púčik"
        patientId: "460527-jozef-pucik"
        lastModified: "2038-12-24T10:05:00Z"
        questions:
          - "Žiadne"
          - "Nie"
          - "Chronická nádcha"
          - "Nie"
          - "Nie"
          - "Áno, ale len občas"
          - "Fyzioterapia a masáže"
          - "Nie"

    QuestionnaireArrayExample:
      summary: Zoznam dvoch dotazníkov
      value:
        - id: 0
          name: "Jožko Púčik"
          patientId: "460527-jozef-pucik"
          lastModified: "2038-12-24T10:05:00Z"
          questions:
            - "Žiadne"
            - "Nie"
            - "Chronická nádcha"
            - "Nie"
            - "Nie"
            - "Áno, ale len občas"
            - "Fyzioterapia a masáže"
            - "Nie"
        - id: 1
          name: "August Cézar"
          patientId: "500110-august-cezar"
          lastModified: "2038-12-24T11:00:00Z"
          questions:
            - "Žiadne"
            - "Nie"
            - "Chronická nádcha"
            - "Nie"
            - "Nie"
            - "Áno, ale len občas"
            - "Fyzioterapia a masáže"
            - "Nie"
